# Credit goes to https://github.com/rust-analyzer/rust-analyzer
name: Draft Release
on:
  push:
    branches:
      - release

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: ["artifacts"]
    steps:
      # The current Airshipper version will be grabbed by running:
      # cargo pkgid | cut -d# -f2 | cut -d: -f2
      - name: Aquire Version
        id: vars
        shell: bash
        run: |
          cd client 
          echo "::set-output name=version::$(cargo pkgid | cut -d# -f2 | cut -d: -f2)"
      - name: Print version
        run: echo "Airshipper v${{ steps.vars.outputs.version }}"
      # Windows msi installer
      - uses: actions/download-artifact@v1
        with:
          name: airshipper-windows-installer
          path: dist
      # Linux
      - uses: actions/download-artifact@v1
        with:
          name: airshipper-Linux
          path: dist
      # MacOS
      - uses: actions/download-artifact@v1
        with:
          name: airshipper-MacOS
          path: dist
      # We got them all!
      - run: ls -all ./dist
      # Draft the release with the assets
      - name: Draft Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true # TODO: Once tested switch to false
          prelease: true
          name: Release v{{ steps.vars.outputs.version }}
          tag_name: v{{ steps.vars.outputs.version }}
          body_path:
          files: ${{ ls ./dist }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
