code-quality:
  extends: .recompile-branch
  stage: check
  image: registry.gitlab.com/veloren/veloren-docker-ci/cache/quality:${CACHE_IMAGE_TAG}
  tags: ["veloren/*", "check"]
  script:
    - cargo clippy --all-targets --locked --all-features -- -D warnings
    - cargo fmt --all -- --check
